name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build & Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build
        run: |
          bash ./scripts/build.sh

      - name: Test
        run: |
          bash ./scripts/test.sh

      - name: Get version
        id: vars
        run: |
          bash ./scripts/version.sh
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.vars.outputs.version }}"
          release_name: "v${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false